### ISSUE TITLE
Pass Schedule parameter to all modules

### ISSUE THREAD

**Issue by joegajeckyj** [awslabs/cid-framework#115]
Inside data-collection/deploy/deploy-data-collection.yaml

Please can you update the template to pass through the Schedule parameter similar to the optimizer module to all modules i.e.

```
ComputeOptimizerModule:
    Type: AWS::CloudFormation::Stack
    Condition: DeployComputeOptimizerModule
    Properties:
      TemplateURL: !Sub "https://${CFNSourceBucket}.s3.amazonaws.com/cfn/data-collection/module-compute-optimizer.yaml"
      Parameters:
        DestinationBucket: !Ref S3Bucket
        ManagementRoleName: !Sub "${ResourcePrefix}${ManagementAccountRole}"
        ManagementAccountID: !Ref ManagementAccountID
        **Schedule: !Ref Schedule**
        ResourcePrefix: !Ref ResourcePrefix
        BucketPrefix:  !Ref DestinationBucket
        RegionsInScope:
          Fn::If:
            - RegionsInScopeIsEmpty
            - !Sub "${AWS::Region}"
            - !Join [ '', !Split [ ' ', !Ref RegionsInScope  ] ] # remove spaces
        LambdaAnalyticsARN: !GetAtt LambdaAnalytics.Arn
        AccountCollectorLambdaARN: !Sub "${AccountCollector.Outputs.LambdaFunctionARN}"
        StepFunctionTemplate: !FindInMap [CodeTemplates, StepFunction, code]
        StepFunctionExecutionRoleARN: !GetAtt StepFunctionExecutionRole.Arn
        SchedulerExecutionRoleARN: !GetAtt SchedulerExecutionRole.Arn
```
